<flux:avatar
    :name="$getName()"
    :src="$getSrc()"
    :initials="$getInitials()"
    :alt="$getAlt()"
    :size="$getSize()"
    :color="$getColor()"
    :color:seed="$getColorSeed()"
    :circle="$getCircle() ?: null"
    :icon="$getIcon()"
    :icon:variant="$getIconVariant()"
    :tooltip="$getTooltip()"
    :tooltip:position="$getTooltipPosition()"
    :badge="$getBadge()"
    :badge:color="$getBadgeColor()"
    :badge:circle="$getBadgeCircle() ?: null"
    :badge:position="$getBadgePosition()"
    :badge:variant="$getBadgeVariant()"
    :as="$getElement()"
    :href="$getHref()"
/>
